blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.index, name='index'),
    path('create/', views.post, name='create'),
    path('post/<int:pk>', views.get_post, name='post_detail'),
    path('update/<int:pk>', views.update_post, name='update'),
    path('delete/<int:pk>', views.delete_post, name='delete'),
    path('category/<int:pk>', views.filter_post, name='category'),
    path('like/<int:pk>', views.post_like, name = 'post_like')

]

posts/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.
class Category(models.Model):
    name  = models.CharField(max_length=255, null=False)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name = 'user')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name = 'category')
    title = models.CharField(max_length=255, null=False)
    description = models.TextField()
    views = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.title

class Like(models.Model):
    user = models.ManyToManyField(CustomUser, related_name='like_user')
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    # likes = models.IntegerField(default=0)

    @classmethod
    def liked(cls, post, user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.add(user)

    @classmethod
    def dislike(cls, post, user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.remove(user)

    def __str__(self):
        return self.user.username

posts/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'category', 'description']


class CommentForm(forms.ModelForm):
    # comment = forms.CharField(required=True)
    class Meta:
        model = Comment
        fields = ['comment']

posts/views.py
from django.db import connection
from django.db.models import F
from django.core.paginator import Paginator
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import PostForm, CommentForm
from .models import Category, Post, Comment, Like

# Create your views here.
def index(request):
    keywords = request.POST.get('search')
   
    if keywords:
        posts = Post.objects.filter(title__icontains=keywords)
    else:
        posts = Post.objects.all().order_by('-created_at')
    
    # title = request.session.get('post_title')
    # print("this is session: ", request.session.get('post_title'))
    categories = Category.objects.all()
    print(categories.query)
    paginator = Paginator(posts, 10)
    page_number  = request.GET.get('page')
    post_pages = paginator.get_page(page_number)
    # print(connection.queries)

    context = {
        'posts':post_pages,
        'categories':categories
    }
    return render(request, 'posts/index.html', context=context)

def post(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST)
        user = request.user
        if form.is_valid():
            post = Post(title = form.cleaned_data['title'], 
                    category=form.cleaned_data['category'], 
                    description = form.cleaned_data['description'], user=user)
            post.save()
            return redirect('index')
    context = {
        'form':form
    }
    return render(request, 'posts/create.html', context=context)

def get_post(request, pk):
    user = request.user
    print(user.id)
    if user.is_authenticated:
        post = Post.objects.get(id=pk)
        # request.session['post_id'] = post.id
        # request.session['post_title'] = post.title
        if not user == post.user:
            Post.objects.filter(id=pk).update(views=F('views')+1)
    posts = Post.objects.get(id=pk)
    comments = Comment.objects.filter(post_id = pk)
    form = CommentForm()
    likes = Like.objects.filter(user = user.id, post_id = pk)
    # if likes:
    #     print("Hes")
    if request.method == 'POST':
        form = CommentForm(request.POST)
        print(form.errors)
        if form.is_valid():
            comment = Comment(user=request.user, post = posts, comment = form.cleaned_data['comment'])
            print(comment)
            comment.save()
            comments = Comment.objects.filter(post_id = pk).values()
            comment_list = list(comments)
            return JsonResponse({'status':'Save', 'comments':comment_list})
        else:
            return JsonResponse({'status':'Not Saved'})
    context = {
        'post': posts,
        'form': form,
        'comments':comments,
        'liked': likes
    }
    return render(request, 'posts/post.html', context = context)

def update_post(request, pk):
    post = Post.objects.get(id = pk)
    form = PostForm(request.POST or None, instance=post)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('post_detail', kwargs={'pk':pk}))
    context ={
        'form':form,
        'user':post.user
    }
    return render(request, 'posts/update.html', context=context)
        
def delete_post(request, pk):
    post = Post.objects.get(id=pk).delete()
    return redirect('index')

def filter_post(request, pk):
    keywords = request.POST.get('search')
    if keywords:
        posts = Post.objects.filter(category_id = pk).filter(title__icontains=keywords)
    else:
        posts = Post.objects.filter(category_id = pk).order_by('-created_at')
        # category = Category.objects.filter(id=pk).get()
        # post = category.category_set()
        print(post)
    categories = Category.objects.all()
    paginator = Paginator(posts, 10)
    page_number  = request.GET.get('page')
    post_pages = paginator.get_page(page_number)
    context = {'posts':post_pages, 'categories':categories}
    return render(request, 'posts/index.html', context = context)


def post_like(request, pk):
    user = request.user
    # post_id = pk

    post = Post.objects.get(id=pk)
    like = Like.objects.filter(user = user, post_id = pk)
    liked = True if like else False

    if liked:
        Like.dislike(post, user)
        liked = False
    else:
        Like.liked(post, user)
        liked = True

    resp = {'like':liked}
    return JsonResponse(resp)

posts/templates/posts/base.html
{% load crispy_forms_tags %}
{% comment %} {% load static %} {% endcomment %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Blog</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% comment %} <link rel="stylesheet" href="{% static 'css/profile.css' %}"> {% endcomment %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://cdn.tiny.cloud/1/qvguvw74gqsmt43ohftpy6yzvu6di568p8wafug5w57jplu8/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> {% endcomment %}

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index'%}">Python</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" method='POST'>
                        {% csrf_token %}
                        <input class="form-control mr-sm-2" type="search" name='search' placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    {% if user.is_authenticated %}
                        <ul class="navbar-nav mr-auto ml-lg-3">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'logout' %}">Logout<span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'profile' user.id%}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href='{% url "create" %}'>Create</a>
                            </li>
                        </ul>
                    {% elif not user.is_authenticated %}
                        <ul class="navbar-nav mr-auto ml-lg-3">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                            </li>
                        </ul>      
                    {% endif %}              
                </div>
            </div>
        </nav>
        <div class="container mt-3">
            <div class="row">
                <div class="col-lg-6">
                    {% block content %} {% endblock %}
                </div>
                <div class="col-lg-6">
                    {%block sidebar %}{% endblock %}
                </div>
            </div>
            <!-- Footer -->
            <footer class="page-footer font-small blue">

                <!-- Copyright -->
                <div class="footer-copyright text-center py-3">© 2021 Copyright:
                    <a href="#"> Pitambar Mahato</a>
                </div>
                <!-- Copyright -->

            </footer>
            <!-- Footer -->
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> {% endcomment %}
        {% block script %}{% endblock %}
    </body>
</html>

posts/templates/posts/create.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if user.is_authenticated %}
        <form method="post" action=''>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center">
                <input type="submit" value="submit" class="btn btn-primary"/>
            </div>
        </form>
    {% else %}
        <h3>Please <a href='{% url "login" %}'>Login</a> to create contents.</h3>
    {% endif %}
{% endblock %}

posts/templates/posts/index.html
{% extends "posts/base.html" %}

{% block content %}
    {% for post in posts %} 
        <div class="card mb-2">
            {% comment %} <img class="card-img-top" src="..." alt="Card image cap"> {% endcomment %}
            <div class="card-body">
                <h5 class="card-title text-capitalize"><a href="{% url 'post_detail' post.id %}" style="text-decoration: none;">{{ post.title }}</a></h5>
                <span><small>Creator : <a href="{% url 'profile' post.user.id %}">{{ post.user.username }}</a> &nbsp;&nbsp; Category : {{ post.category.name }} &nbsp;&nbsp; Created : {{ post.created_at.date}} &nbsp;&nbsp; |&nbsp;&nbsp; {{ post.views }} Views</small></span>
                <span><p class="card-text">{{ post.description|safe|truncatewords:"50"|linebreaks }}</p>
                <a href="{% url 'post_detail' post.id %}">read more</a></span>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
    {% endfor %}
    <div class="pagination col-lg-6 offset-lg-3">
        <span class="step-links">
            {% if posts.has_previous %}   
                <a href="?page=1" class="btn btn-primary">&laquo; first</a>&nbsp;   
                <a href="?page={{ posts.previous_page_number }}" class="btn btn-primary">previous</a>&nbsp;
                
            {% endif %}
            {% if posts.has_previous or posts.has_next %}
                <span class="current">
                    {{ posts.number }}
                </span>&nbsp;
            {% endif %}

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}" class="btn btn-primary">next</a>&nbsp;
                <a href="?page={{ posts.paginator.num_pages }}" class="btn btn-primary">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}
{% block sidebar %}
    <h4>Categories</h4>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'category' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

posts/templates/posts/post.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mb-2">
        {% comment %} <img class="card-img-top" src="..." alt="Card image cap"> {% endcomment %}
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-lg-8">
                    <h5 class="card-title mb-0 text-capitalize"><a href="{% url 'post_detail' post.id %}"  style="text-decoration: none">{{ post.title }}</a></h5>
                    <span><small>Category: <a href="#" style="text-decoration: none">{{ post.category.name }}</a></small>&nbsp;&nbsp;<small>Created: {{ post.created_at.date }}</small></span>
                </div>
                <div class="col-lg-2 mt-2">
                    <a href="{% url 'delete' post.id %}"><button class="btn btn-danger">Delete</button></a>
                </div>
                <div class="col-lg-2 mt-2">
                    <a href="{% url 'update' post.id %}"><button class="btn btn-success">Update</button></a>
                </div>
            </div>
            
            <p class="card-text">{{ post.description }}</p>

            <div class="row mb-3">
                <div class="col-lg-2 mt-2">
                    {% if liked %}
                        <a class="btn btn-primary" id="btnLike" href = "{% url 'post_like' post.id %}">UnLike</a>
                    {% elif not liked %}
                        <a class="btn btn-primary" id="btnLike" href = "{% url 'post_like' post.id %}">Like</a>
                    {% endif %}
                </div>
                <div class="col-lg-2 mt-2">
                    <button class="btn btn-primary" id="commentBtn">Comment</button>
                </div>
            </div>
        </div>
        
        <div class="card-footer">
            <small class="text-muted">Last updated at {{ post.updated_at.date }}</small>
        </div>
    </div>
    <div class="comment-widgets" id='comment_list'>
        <!-- Comment Row -->
        {% for comment in comments %}
            <div class="d-flex flex-row comment-row m-t-0 mt-4">
                <div class="p-2"><img src="https://i.imgur.com/Ur43esv.jpg" alt="user" width="50" class="rounded-circle"></div>
                <div class="comment-text w-100">
                    <h6 class="font-medium text-capitalize">{{ comment.user.username }}</h6> <span class="m-b-15 d-block">{{ comment.comment }}</span>
                    <div class="comment-footer mt-2"> <span class="text-muted float-right">{{ comment.created_at.date }}</span> <button type="button" class="btn btn-primary btn-sm">Edit</button> <button type="button" class="btn btn-success btn-sm">Publish</button> <button type="button" class="btn btn-danger btn-sm">Delete</button> </div>
                </div>
            </div> <!-- Comment Row -->
        {% endfor %}
    </div>
    <div class="bg-success p-3 rounded text-light text-center m-2" id = 'successful'>
        <h4 id = 'success_message'></h4>

    </div>
    <div id = "comment">
        <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" id="cmtBtn" class="btn btn-primary">Submit</button>
        </form>
    </div>

    
{% endblock %}

{% block sidebar %}
    <h4>Related Articles</h4>
{% endblock %}
{% block script %}
    <script>
        $("#comment").hide();
        $("#successful").hide();
        $('#cmtBtn').click(function(e){
            e.preventDefault();
            output = "";
            console.log("Submit button clicked");
            let comment = $('#id_comment').val();
            let csrf = $('input[name=csrfmiddlewaretoken]').val();
            console.log(comment);
            if(comment === ""){
                console.log("comment is empty");
            }
            mydata = {comment: comment, csrfmiddlewaretoken: csrf};
            $.ajax({
                url: {{ post.id }},
                method: "POST",
                data: mydata,
                success: function(data){
                    comment = data.comments;
                    for(i=0; i<comment.length; i++){
                        output += '<div class="d-flex flex-row comment-row m-t-0 mt-4">\
                                <div class="p-2"><img src="https://i.imgur.com/Ur43esv.jpg" alt="user" width="50" class="rounded-circle"></div>\
                                <div class="comment-text w-100">\
                                    <h6 class="font-medium text-capitalize">'+comment[i].user.username+'</h6> <span class="m-b-15 d-block">'+comment[i].comment+'</span>\
                                    <div class="comment-footer mt-2"> <span class="text-muted float-right">'+comment[i].created_at.date+'</span> <button type="button" class="btn btn-primary btn-sm">Edit</button> <button type="button" class="btn btn-success btn-sm">Publish</button> <button type="button" class="btn btn-danger btn-sm">Delete</button> </div>\
                                </div>\
                            </div>'
                    }
                    $('#comment_list').html(output);
                    $('#id_comment').val("");
                    $('#successful').show();
                    $('#success_message').text("Comment Successfully Submitted.");
                    console.log(data.comments);
                },
                error: function(data){
                    console.log(data);
                }
            });
        });
        $("#btnLike").click(function(e){
            e.preventDefault();
            var href = this.href;
            $.ajax({
                url: href,
                success:function(response){
                    console.log(response);
                    if(response['like']){
                        $("#btnLike").html("Unlike")
                    }else{
                        $('#btnLike').html("Like")
                    }
            }
            })
                
        });
        $("#commentBtn").click(function(e){
            e.preventDefault();
            $("#comment").show();
        })
    </script>
{% endblock %}

posts/templates/posts/update.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
        {% comment %} <img class="card-img-top" src="..." alt="Card image cap"> {% endcomment %}
            <form method="post" action=''>
                {% csrf_token %}
                {% comment %} <div class="form-group">Title: {{form.title}}</div>
                <div class="form-group">Category: {{form.category}}</div>
                <div class="form-group">Description: {{form.description}}</div> {% endcomment %}
                {{ form|crispy }}
                <input type="submit" value="submit" class="btn btn-primary"/>
            </form>

{% endblock %}

{% block sidebar %}
    <h4>Related Articles</h4>
{% endblock %}